### ISSUE TITLE
Function not implemented in pv

### ISSUE THREAD

**Issue by john-craft** [gerner/autodevstats#1]
**Environment**
WSL 1 on Windows 10 version 1909
pv 1.6.6

**Problem**
While running `statstool` on a local repo, the application crashes in `fetch-comments.sh` with the error `pv: Function not implemented` while trying to parse commit comments (screen shot below).

![image](https://user-images.githubusercontent.com/890318/87087385-d5651880-c1e7-11ea-889d-82ba4cffd985.png)

**Comment by gerner** [comment]
@john-craft it looks like pv isn't installed on your machine (or perhaps there's some mismatch in the version you're using and the way the tool is using pv?) I'm a little surprised because the tool should have bailed sooner when it does the dependency check.

Do you mind pasting in a little more of the tool's output? There should be a block that looks something like this (although the version specific stuff will likely be different):

```
checking for dependencies...
checking for curl...
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
checking for git...
git version 2.27.0
checking for awk...
GNU Awk 4.1.4, API: 1.1 (GNU MPFR 4.0.1, GNU MP 6.1.2)
checking for join...
join (GNU coreutils) 8.28
checking for pv...
pv 1.6.6 - Copyright 2015 Andrew Wood <andrew.wood@ivarch.com>
checking for ag...
ag version 2.1.0
dependencies look good
```

**Comment by john-craft** [comment]
![image](https://user-images.githubusercontent.com/890318/87093190-a784d180-c1f1-11ea-830e-76c339f37cd9.png)

**Comment by gerner** [comment]
@john-craft Thank you. And I see you actually gave me most of what I needed in your original post. I should not have doubted you or WSL.

It looks like pv has a couple of issues on Cygwin and perhaps also on WSL. From the pv man page:

```
KNOWN PROBLEMS
       The following problems are known to exist in pv:

       *      The  -c  option  does  not work properly on Cygwin without cygserver running, if started near the bottom of the screen
              (IPC is needed to handle the terminal scrolling).  To fix this, start cygserver before using pv -c.

       *      The -R option is not available on Cygwin without cygserver running (SYSV IPC is needed). To fix this, start  cygserver
              before running the instance of pv you want, at runtime, to change the parameters of.

       If you find any other problems, please report them.
```

The tool is doing something sort of convoluted and purely for cosmetic reasons here. So I made a change that will just silently ignore this if it happens.

Can you please git pull and give the tool another try?

**Comment by john-craft** [comment]
> Can you please git pull and give the tool another try?

Success! I will send you the output of the tool.

**Comment by gerner** [comment]
Awesome, thanks!
